#!/bin/bash

# Script para corrigir repositórios APT duplicados no Ubuntu
# Resolve o problema: "Target ... is configured multiple times"

echo "🔧 Corrigindo repositórios APT duplicados..."

# Fazer backup dos arquivos de sources
echo "📋 Fazendo backup dos sources..."
sudo cp -r /etc/apt/sources.list.d /etc/apt/sources.list.d.backup-$(date +%Y%m%d-%H%M%S)
sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup-$(date +%Y%m%d-%H%M%S)

# Remover arquivo problemático duplicado
if [[ -f "/etc/apt/sources.list.d/ubuntu-mirrors.list" ]]; then
    echo "🗑️ Removendo arquivo duplicado ubuntu-mirrors.list..."
    sudo rm -f /etc/apt/sources.list.d/ubuntu-mirrors.list
fi

# Limpar outros arquivos problemáticos comuns
sudo rm -f /etc/apt/sources.list.d/*duplicate*
sudo rm -f /etc/apt/sources.list.d/*backup*

# Recriar sources.list limpo para Ubuntu 22.04
echo "📝 Recriando sources.list limpo..."
sudo tee /etc/apt/sources.list > /dev/null << 'EOF'
# Ubuntu 22.04 LTS (Jammy Jellyfish) - Sources List
# Generated by N.Crisis installer

# Main repository
deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse

# Security updates
deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
deb-src http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse

# Updates
deb http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ jammy-updates main restricted universe multiverse

# Backports
deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse
EOF

# Remover arquivos de cache corrompidos
echo "🧹 Limpando cache APT..."
sudo rm -rf /var/lib/apt/lists/*
sudo rm -rf /var/cache/apt/*.bin

# Recriar cache
echo "🔄 Atualizando repositórios..."
sudo apt clean
sudo apt update

echo "✅ Correção APT concluída!"
echo "ℹ️ Backups salvos com timestamp para restauração se necessário"

# Verificar se ainda há warnings
echo "🔍 Verificando se há warnings restantes..."
if sudo apt update 2>&1 | grep -q "is configured multiple times"; then
    echo "⚠️ Ainda existem warnings - executando limpeza adicional..."
    
    # Limpeza mais agressiva
    sudo find /etc/apt/sources.list.d/ -name "*.list" -exec grep -l "jammy" {} \; | while read file; do
        echo "Verificando: $file"
        # Remove duplicatas baseadas no conteúdo
        sudo sort "$file" | sudo uniq > "/tmp/$(basename "$file")"
        sudo mv "/tmp/$(basename "$file")" "$file"
    done
    
    sudo apt update
else
    echo "✅ Nenhum warning encontrado - repositórios limpos!"
fi